[sncast.dev]                                         # Define a profile name
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/dql5pMT88iueZWl7L0yzT56uVk0EBU4L" # Url of the RPC provider
account = "my_account"
block-explorer = "Voyager"

[sncast.release]                                         # Define a profile name
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_10/dql5pMT88iueZWl7L0yzT56uVk0EBU4L" # Url of the RPC provider
account = "my_account"
block-explorer = "Voyager"